[colors.primary]
background = "#ffffff"
foreground = "#000000"

[colors.cursor]
text = "#ffffff"
cursor = "#000000"

[colors.vi_mode_cursor]
text = "#ffffff"
cursor = "#000000"

[colors.search.matches]
foreground = "#ffffff"
background = "#000000"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#957777"
background = "#000000"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#ffffff"
red = "#a38b8b"
green = "#b49a9a"
yellow = "#745108"
blue = "#bf8c4d"
magenta = "#a78e8e"
cyan = "#b69b9b"
white = "#584b4b"

[colors.bright]
black = "#957777"
red = "#a38b8b"
green = "#b49a9a"
yellow = "#926e38"
blue = "#947e7e"
magenta = "#a78e8e"
cyan = "#b69b9b"
white = "#000000"

[colors.dim]
black = "#000000"
red = "#a38b8b"
green = "#b49a9a"
yellow = "#926e38"
blue = "#947e7e"
magenta = "#a78e8e"
cyan = "#b69b9b"
white = "#957777"
