[colors.primary]
background = "#000000"
foreground = "#f6eae4"

[colors.cursor]
text = "#000000"
cursor = "#f6eae4"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#f6eae4"

[colors.search.matches]
foreground = "#000000"
background = "#f6eae4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#b9aeae"
background = "#f6eae4"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#000000"
red = "#e3bebe"
green = "#f1c8c8"
yellow = "#f1cc9f"
blue = "#ceae77"
magenta = "#efd3c6"
cyan = "#c5b6b6"
white = "#f3e2e2"

[colors.bright]
black = "#b9aeae"
red = "#ffc5c5"
green = "#fde0e0"
yellow = "#f6dca5"
blue = "#ecd0ac"
magenta = "#dfcebf"
cyan = "#e5dbdb"
white = "#f6eae4"

[colors.dim]
black = "#f6eae4"
red = "#ffc5c5"
green = "#fde0e0"
yellow = "#f6dca5"
blue = "#ecd0ac"
magenta = "#dfcebf"
cyan = "#e5dbdb"
white = "#b9aeae"
