[colors.primary]
background = "#09090e"
foreground = "#d9dded"

[colors.cursor]
text = "#09090e"
cursor = "#d9dded"

[colors.vi_mode_cursor]
text = "#09090e"
cursor = "#d9dded"

[colors.search.matches]
foreground = "#09090e"
background = "#d9dded"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#383a4a"
background = "#d9dded"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#09090e"
red = "#f7adc2"
green = "#c3ecbf"
yellow = "#fdf3de"
blue = "#afccfc"
magenta = "#e4d1fb"
cyan = "#b0eae0"
white = "#fdfdff"

[colors.bright]
black = "#383a4a"
red = "#f7adc2"
green = "#c3ecbf"
yellow = "#fdf3de"
blue = "#afccfc"
magenta = "#e4d1fb"
cyan = "#b0eae0"
white = "#d9dded"

[colors.dim]
black = "#d9dded"
red = "#f7adc2"
green = "#c3ecbf"
yellow = "#fdf3de"
blue = "#afccfc"
magenta = "#e4d1fb"
cyan = "#b0eae0"
white = "#383a4a"
